### ISSUE TITLE
[TIP] Ubuntu 23.10 installation

### ISSUE THREAD

**Issue by MusicMaker** [midi2-dev/MIDI2.0Workbench#6]
Ubuntu with Linux kernel 6.5 is on nodejs 18, the reop need Node 16, Tying to install 16 
The installation instruction refer to yarn but actually yarnpkg is needed. 

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
nvm install 16
nvm use 16
git clone https://github.com/midi2-dev/MIDI2.0Workbench.git
cd MIDI*
sudo apt-get install yarnpkg
yanrpkg

**Comment by starfishmod** [comment]
Added tip to read.me - Thanks!

**Comment by MusicMaker** [comment]
For some strange reason could not run it anymore with npm 16


changed the process to :

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
nvm install 18
nvm use 18
git clone https://github.com/midi2-dev/MIDI2.0Workbench.git
cd MIDI*
sudo apt-get install yarnpkg
yanrpkg
yarnpkg run start


 log of build:

@yanrpkg
yarn install v1.22.21
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning node-gyp > npmlog@6.0.2: This package is no longer supported.
warning node-gyp > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning node-gyp > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning node-gyp > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning node-gyp > npmlog > gauge@4.0.4: This package is no longer supported.
warning node-gyp > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning node-gyp > npmlog > are-we-there-yet@3.0.1: This package is no longer supported.
warning node-gyp > make-fetch-happen > cacache > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning node-gyp > make-fetch-happen > cacache > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning node-gyp > make-fetch-happen > cacache > @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
warning node-gyp > make-fetch-happen > cacache > @npmcli/move-file > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning glob@7.2.3: Glob versions prior to v9 are no longer supported
warning Resolution field "automation-events@4.0.14" is incompatible with requested version "automation-events@^7.0.5"
warning electron-builder > app-builder-lib > electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
warning electron-builder > app-builder-lib > @electron/universal > asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
warning electron-builder > app-builder-lib > @electron/universal > asar > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning electron-icon-builder > icon-gen > del > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning electron-icon-builder > icon-gen > svg2png > phantomjs-prebuilt@2.1.16: this package is now deprecated
warning electron-icon-builder > icon-gen > svg2png > phantomjs-prebuilt > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning electron-icon-builder > icon-gen > svg2png > phantomjs-prebuilt > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning electron-icon-builder > jimp > @jimp/custom > @jimp/core > phin@2.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning electron-icon-builder > jimp > @jimp/custom > @jimp/core > load-bmfont > phin@2.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning electron-icon-builder > icon-gen > svg2png > phantomjs-prebuilt > request > har-validator@5.1.5: this library is no longer supported
[2/4] Fetching packages...
**error node-addon-api@8.0.0: The engine "node" is incompatible with this module. Expected version "^18 || ^20 || >= 21". Got "16.20.2"**
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
