### ISSUE TITLE
Baud rate and ping

### ISSUE THREAD

**Issue by MusicMaker** [midi2-dev/MIDI2.0Workbench#9]
These are deprecated or undocumented ?

![image](https://github.com/midi2-dev/MIDI2.0Workbench/assets/7860894/f6c4bf0d-3081-4bc0-a049-f69d11bdf40b)

**Comment by starfishmod** [comment]
You saw nothing :eyes:  :laughing: 
This is experimental and is not supposed to be in this version. Thanks for pointing it out - I have now removed this.
